---
# DevSpaces CheCluster for aap-demo
# Simplified from RDU cluster config for single-node MicroShift
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-devspaces
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard:
      logLevel: ERROR
    devWorkspace: {}
    devfileRegistry: {}
    imagePuller:
      enable: false
      spec: {}
    metrics:
      enable: true
    pluginRegistry: {}
  containerRegistry: {}
  devEnvironments:
    defaultNamespace:
      autoProvision: true
      template: <username>-devspaces
    disableContainerRunCapabilities: false
    imagePullPolicy: IfNotPresent
    maxNumberOfRunningWorkspacesPerUser: 2
    persistUserHome:
      enabled: true
    secondsOfInactivityBeforeIdling: 3600
    startTimeoutSeconds: 600
    storage:
      perUserStrategyPvcConfig:
        claimSize: 10Gi
        storageClass: local-path
      pvcStrategy: per-user
  gitServices: {}
  networking:
    domain: apps.127.0.0.1.nip.io
