---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-27/ee-supported-rhel9:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_final: |
    # Install OpenShift CLI and Skopeo
    RUN microdnf install -y openshift-clients skopeo && \
        microdnf clean all

    # Verify installations
    RUN oc version --client && skopeo --version
