#!/usr/bin/env bash
# Setup bridged networking for portal VM on macOS
# Uses socket_vmnet to give VM real IP on host network

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

error() { echo -e "${RED}ERROR: $*${NC}" >&2; }
warn() { echo -e "${YELLOW}WARN: $*${NC}" >&2; }
info() { echo -e "${GREEN}INFO: $*${NC}"; }

check_socket_vmnet() {
  if ! command -v socket_vmnet &>/dev/null; then
    error "socket_vmnet not found"
    echo ""
    echo "Install with:"
    echo "  brew install socket_vmnet"
    echo ""
    echo "Post-install setup:"
    echo "  # Create vmnet group"
    echo "  sudo dscl . -create /Groups/vmnet"
    echo "  sudo dscl . -create /Groups/vmnet PrimaryGroupID 1001"
    echo ""
    echo "  # Add your user to vmnet group"
    echo "  sudo dseditgroup -o edit -a \$USER -t user vmnet"
    echo ""
    echo "  # Configure socket_vmnet"
    echo "  sudo /opt/homebrew/opt/socket_vmnet/bin/socket_vmnet_client \\"
    echo "    /var/run/socket_vmnet config"
    echo ""
    echo "See: https://github.com/lima-vm/socket_vmnet"
    exit 1
  fi

  # Check if socket_vmnet service is running
  if ! pgrep -x socket_vmnet >/dev/null; then
    warn "socket_vmnet service not running"
    echo ""
    echo "Start with:"
    echo "  sudo brew services start socket_vmnet"
    echo ""
    echo "Or run manually:"
    echo "  sudo /opt/homebrew/opt/socket_vmnet/bin/socket_vmnet \\"
    echo "    --vmnet-mode=bridged \\"
    echo "    --vmnet-interface=en0 \\"
    echo "    /var/run/socket_vmnet"
    exit 1
  fi

  info "✓ socket_vmnet installed and running"
}

get_host_ip() {
  # Get primary interface IP (en0)
  local host_ip
  host_ip=$(ifconfig en0 | awk '/inet / {print $2}')

  if [ -z "$host_ip" ]; then
    error "Failed to get host IP from en0"
    exit 1
  fi

  echo "$host_ip"
}

generate_vmnet_config() {
  local host_ip="$1"
  local portal_dir="${2:-$HOME/.aap-demo/portal-vm}"

  mkdir -p "$portal_dir"

  cat > "$portal_dir/vmnet-config.txt" <<EOF
# socket_vmnet configuration for portal VM
# Generated by setup-networking.sh

HOST_IP=$host_ip
VMNET_SOCKET=/var/run/socket_vmnet
VMNET_MODE=bridged
VMNET_INTERFACE=en0

# AAP routes will use <host-ip>.nip.io instead of 127.0.0.1.nip.io
# Example: https://aap-aap-operator.apps.$host_ip.nip.io

# QEMU arguments to add:
# -netdev socket,id=net0,fd=3 \
# -device virtio-net-pci,netdev=net0,mac=52:55:00:d1:55:01 \
# 3<> /var/run/socket_vmnet
EOF

  info "✓ Config written to: $portal_dir/vmnet-config.txt"
  echo ""
  echo "Host IP: $host_ip"
  echo "AAP route pattern: https://aap-aap-operator.apps.$host_ip.nip.io"
}

# Main
info "Setting up bridged networking for portal VM..."
echo ""

check_socket_vmnet

HOST_IP=$(get_host_ip)
PORTAL_DIR="${1:-$HOME/.aap-demo/portal-vm}"

generate_vmnet_config "$HOST_IP" "$PORTAL_DIR"

echo ""
info "Next steps:"
echo "  1. Update deploy.sh to use socket_vmnet networking"
echo "  2. Modify cloud-init aap.host_url to use $HOST_IP.nip.io"
echo "  3. Test VM connectivity: ping $HOST_IP (from VM)"
