---
# defaults for apme_helm_values

apme_helm_values_template: "{{ role_path }}/files/portal-apme-values.yaml.template"
apme_helm_values_check_ssl: false  # Set to true for production with valid certs
