"""Golden-file tests for every rendered manifest (design §14 R6).

R6's instruction is explicit: switching from bash's ``awk``/``sed`` text
munging to real YAML manipulation is the right call, *and* the rendered output
must be pinned against what bash actually produces. The fixtures under
``tests/fixtures/golden/`` were generated by running bash's own pipelines
verbatim against ``config/`` — the exact commands are recorded next to each
fixture below.

Comparison is on the **parsed document**, not the text. Comments, key order
and blank lines differ by construction once a YAML round-trip replaces a
stream editor; what must not differ is the data the API server receives, and
that is what these assert.

One divergence is deliberate and has its own test:
:func:`test_subscription_channel_substitution_is_fixed`.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

import pytest
import yaml

from aap_demo.cluster import aap as aap_mod
from aap_demo.cluster import olm, storage

GOLDEN = Path(__file__).resolve().parents[1] / "fixtures" / "golden"
NAMESPACE = "aap-operator"


def load_golden(name: str) -> Dict[str, Any]:
    return yaml.safe_load((GOLDEN / name).read_text(encoding="utf-8"))


def load_golden_all(name: str) -> Any:
    return list(yaml.safe_load_all((GOLDEN / name).read_text(encoding="utf-8")))


# ---------------------------------------------------------------------------
# OLM manifests
# ---------------------------------------------------------------------------


def test_catalogsource_matches_bash_sed() -> None:
    """bash: ``sed -e s|redhat-operator-index:v[0-9.]*|…v4.22| -e s|namespace: aap-operator|…|``."""
    rendered = yaml.safe_load(olm.render_catalogsource(NAMESPACE, "4.22"))
    assert rendered == load_golden("catalogsource.aap-operator.4.22.yaml")
    assert rendered["spec"]["image"].endswith("redhat-operator-index:v4.22")


def test_catalogsource_rewrites_only_the_index_tag() -> None:
    rendered = yaml.safe_load(olm.render_catalogsource("other-ns", "4.19"))
    assert rendered["spec"]["image"] == ("registry.redhat.io/redhat/redhat-operator-index:v4.19")
    assert rendered["metadata"]["namespace"] == "other-ns"
    assert rendered["spec"]["secrets"] == ["redhat-operators-pull-secret"]


def test_operatorgroup_matches_bash_sed() -> None:
    """bash: ``sed -e s|namespace: aap|…|g -e s|name: aap-og|…| -e s|- aap|…|``."""
    rendered = yaml.safe_load(olm.render_operatorgroup(NAMESPACE))
    assert rendered == load_golden("operatorgroup.aap-operator.yaml")
    assert rendered["metadata"]["name"] == "aap-operator-og"
    assert rendered["spec"]["targetNamespaces"] == [NAMESPACE]


def test_subscription_matches_bash_sed_at_the_default_channel() -> None:
    rendered = yaml.safe_load(olm.render_subscription(NAMESPACE, "stable-2.7"))
    assert rendered == load_golden("subscription.aap-operator.stable-2.7.yaml")


def test_subscription_leaves_source_namespace_alone() -> None:
    """bash's ``s|namespace: aap|…|`` has no ``g`` and is case-sensitive.

    ``sourceNamespace:`` therefore never matched, and it stays hardcoded to
    ``aap-operator``. Reproduced rather than fixed: R6 sanctions exactly one
    deliberate behavior change here (the channel), and quietly repointing the
    Subscription's source would be a second one.
    """
    rendered = yaml.safe_load(olm.render_subscription("custom-ns", "stable-2.7"))
    assert rendered["metadata"]["namespace"] == "custom-ns"
    assert rendered["spec"]["sourceNamespace"] == "aap-operator"


def test_subscription_channel_substitution_is_fixed() -> None:
    """R6's dead ``sed``: bash asked for 2.6 and silently installed 2.7.

    ``config/olm/subscription.yaml`` says ``channel: stable-2.7`` while the
    sed pattern still says ``channel: stable-2.6``, so the substitution has
    matched nothing since the 2.7 bump. The golden fixture records that:
    running bash's pipeline with ``AAP_CHANNEL=stable-2.6`` still emits
    ``stable-2.7``. The port sets ``spec.channel`` unconditionally.
    """
    bash_output = load_golden("subscription.aap-operator.stable-2.6.BUGGY.yaml")
    assert bash_output["spec"]["channel"] == "stable-2.7", (
        "fixture no longer demonstrates the bug — regenerate it from bash"
    )

    rendered = yaml.safe_load(olm.render_subscription(NAMESPACE, "stable-2.6"))
    assert rendered["spec"]["channel"] == "stable-2.6"
    # Everything *else* still matches what bash emitted.
    assert {k: v for k, v in rendered.items() if k != "spec"} == {
        k: v for k, v in bash_output.items() if k != "spec"
    }


# ---------------------------------------------------------------------------
# Storage PVCs
# ---------------------------------------------------------------------------


def test_storage_pvcs_match_bash_sed() -> None:
    """bash: ``sed -e s/__NAMESPACE__/…/g -e s/__AAP_NAME__/…/g``."""
    template = _package_text("aap_demo.data.manifests", "aap-storage-pvcs.yaml")
    rendered = list(
        yaml.safe_load_all(storage.render_pvcs(template, namespace=NAMESPACE, aap_name="aap"))
    )
    assert rendered == load_golden_all("aap-storage-pvcs.aap-operator.aap.yaml")


def test_storage_pvc_names_compose_the_aap_name() -> None:
    template = _package_text("aap_demo.data.manifests", "aap-storage-pvcs.yaml")
    docs = list(yaml.safe_load_all(storage.render_pvcs(template, namespace="ns", aap_name="myaap")))
    names = {doc["metadata"]["name"] for doc in docs}
    assert names == {"postgres-15-myaap-postgres-15-0", "myaap-hub-redis-data"}
    assert all(doc["spec"]["storageClassName"] == "nfs-local-rwx" for doc in docs)


# ---------------------------------------------------------------------------
# CR templates
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "cr_name",
    ["minimal", "controller", "controller-eda", "minimal-rwx"],
)
def test_cr_matches_bash_awk(cr_name: str) -> None:
    """bash: ``awk '/storage_type: file/{print; print "    route_host: " host; next}…'``."""
    rendered = yaml.safe_load(aap_mod.render_cr(aap_mod.load_cr(cr_name), namespace=NAMESPACE))
    assert rendered == load_golden(f"cr.{cr_name}.{NAMESPACE}.yaml")


def test_controller_cr_gets_no_route_host() -> None:
    """The awk keys on ``storage_type: file``; the controller CR has no hub."""
    rendered = yaml.safe_load(aap_mod.render_cr(aap_mod.load_cr("controller"), namespace=NAMESPACE))
    assert rendered["spec"]["hub"] == {"disabled": True}
    assert "route_host" not in yaml.safe_dump(rendered)


def test_minimal_cr_route_host_lands_under_hub() -> None:
    rendered = yaml.safe_load(aap_mod.render_cr(aap_mod.load_cr("minimal"), namespace="other-ns"))
    assert rendered["spec"]["hub"]["route_host"] == ("aap-hub-other-ns.apps.127.0.0.1.nip.io")
    assert "route_host" not in rendered["spec"]


def test_noingress_cr_matches_bash_sed() -> None:
    rendered = yaml.safe_load(
        aap_mod.render_cr(
            aap_mod.load_cr("minimal-noingress"),
            namespace=NAMESPACE,
            public_url="https://aap.example.com",
            noingress=True,
        )
    )
    assert rendered == load_golden("cr.minimal-noingress.public.yaml")


def test_every_bundled_cr_is_renderable() -> None:
    """A CR added to the package data must not silently break the deploy path."""
    for name in aap_mod.available_crs():
        template = aap_mod.load_cr(name)
        if "noingress" in name:
            aap_mod.render_cr(template, namespace="ns", public_url="https://x", noingress=True)
        else:
            aap_mod.render_cr(template, namespace="ns")


def _package_text(package: str, name: str) -> str:
    from importlib.resources import files

    return files(package).joinpath(name).read_text(encoding="utf-8")
