"""YAML configuration: load, layered resolution, validation, save (design §5.1, §5.3).

Comments in ``config.yaml`` are ours, not the user's: the header block is
regenerated on every write rather than round-tripped, which is what lets the
file keep a schema-driven key order without a comment-preserving YAML library
(§5.1, option 1).

PyYAML is used in pure-Python mode only — ``safe_load``/``safe_dump``, never
``CSafeLoader``/``CSafeDumper`` — so installing aap-demo never needs a compiler.
"""

from __future__ import annotations

import copy
import os
from pathlib import Path
from typing import Any, Dict, Mapping, Optional

import yaml

from aap_demo.core import schema
from aap_demo.core.errors import ConfigError

SCHEMA_VERSION = 1

_HEADER = """\
# aap-demo configuration. Generated by aap-demo {version}.
# Docs: https://github.com/RedHatOfficial/aap-demo/blob/main/docs/CONFIG.md
# Edit with: aap-demo config edit
# This file contains NO credentials. Secrets live in the OS credential store;
# inspect them with `aap-demo config secrets list`.
"""

_TRUE = {"1", "true", "yes", "on"}
_FALSE = {"0", "false", "no", "off"}


def _coerce(value: str, prop: Mapping[str, Any]) -> Any:
    prop_type = prop.get("type")
    if prop_type == "boolean":
        lowered = value.strip().lower()
        if lowered in _TRUE:
            return True
        if lowered in _FALSE:
            return False
        return value
    if prop_type == "integer":
        try:
            return int(value)
        except ValueError:
            return value
    if prop_type == "number":
        try:
            return float(value)
        except ValueError:
            return value
    if prop_type == "array":
        return [item for item in (v.strip() for v in value.split(",")) if item]
    return value


def _deep_merge(base: Dict[str, Any], overlay: Mapping[str, Any]) -> Dict[str, Any]:
    out = copy.deepcopy(base)
    for key, value in overlay.items():
        if isinstance(value, Mapping) and isinstance(out.get(key), dict):
            out[key] = _deep_merge(out[key], value)
        else:
            out[key] = copy.deepcopy(value)
    return out


def read_yaml(path: Path) -> Dict[str, Any]:
    if not path.is_file():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if data is None:
        return {}
    if not isinstance(data, dict):
        raise ConfigError(f"{path}: expected a YAML mapping at the top level")
    return data


def env_overlay(env: Optional[Mapping[str, str]] = None) -> Dict[str, Dict[str, Any]]:
    """Values contributed by environment variables, via the schema's x-env map."""
    environ = os.environ if env is None else env
    overlay: Dict[str, Dict[str, Any]] = {}
    for var, (section_name, key) in schema.env_map().items():
        if var not in environ:
            continue
        raw = environ[var]
        if raw == "":
            continue
        prop = schema.section(section_name)["properties"][key]
        overlay.setdefault(section_name, {})[key] = _coerce(raw, prop)
    return overlay


class Config:
    """A resolved, validated configuration plus the file it came from."""

    def __init__(self, data: Dict[str, Any], *, path: Optional[Path] = None) -> None:
        self.data = data
        self.path = path

    # -- access -------------------------------------------------------------

    def get(self, dotted: str, default: Any = None) -> Any:
        node: Any = self.data
        for part in dotted.split("."):
            if not isinstance(node, dict) or part not in node:
                return default
            node = node[part]
        return node

    def set(self, dotted: str, value: Any) -> None:
        known = schema.config_paths()
        if dotted in known:
            section_name, key = known[dotted]
            prop = schema.section(section_name)["properties"][key]
            if isinstance(value, str):
                value = _coerce(value, prop)
        parts = dotted.split(".")
        node = self.data
        for part in parts[:-1]:
            node = node.setdefault(part, {})
            if not isinstance(node, dict):
                raise ConfigError(f"{dotted}: cannot set a key under a scalar value")
        node[parts[-1]] = value
        self.validate()

    def section(self, name: str) -> Dict[str, Any]:
        value = self.data.get(name, {})
        return value if isinstance(value, dict) else {}

    def validate(self) -> None:
        schema.validate(self.data)

    def as_dict(self) -> Dict[str, Any]:
        return copy.deepcopy(self.data)

    # -- persistence --------------------------------------------------------

    def save(self, path: Optional[Path] = None, *, version: Optional[str] = None) -> Path:
        target = path or self.path
        if target is None:
            raise ConfigError("no config path to save to")
        write(target, self.data, version=version)
        self.path = target
        return target


def _ordered(data: Mapping[str, Any]) -> Dict[str, Any]:
    """Key order from the schema, so the file's shape tracks the schema."""
    out: Dict[str, Any] = {}
    if "schema_version" in data:
        out["schema_version"] = data["schema_version"]
    for name in schema.sections():
        if name not in data:
            continue
        block = data[name]
        if not isinstance(block, dict):
            out[name] = block
            continue
        props = schema.section(name)["properties"]
        order = sorted(props, key=lambda k: props[k].get("x-order", 1000))
        ordered_block = {k: block[k] for k in order if k in block}
        ordered_block.update({k: v for k, v in block.items() if k not in ordered_block})
        out[name] = ordered_block
    out.update({k: v for k, v in data.items() if k not in out})
    return out


def write(path: Path, data: Mapping[str, Any], *, version: Optional[str] = None) -> None:
    """Atomically write config.yaml with a regenerated header."""
    from aap_demo import __version__

    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(_ordered(data), sort_keys=False, default_flow_style=False)
    text = _HEADER.format(version=version or __version__) + body
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    os.replace(str(tmp), str(path))


def resolve(
    *,
    file_data: Optional[Mapping[str, Any]] = None,
    env: Optional[Mapping[str, str]] = None,
    overrides: Optional[Mapping[str, Mapping[str, Any]]] = None,
    path: Optional[Path] = None,
) -> Config:
    """Layer defaults < file < env < explicit overrides, then validate once.

    One validator call over the merged result is what makes a bad value read the
    same whether it arrived from a flag, an env var, the file, or the API (§9.3).
    """
    data = schema.defaults()
    data["schema_version"] = SCHEMA_VERSION
    if file_data:
        data = _deep_merge(data, file_data)
    data = _deep_merge(data, env_overlay(env))
    if overrides:
        data = _deep_merge(data, overrides)
    core = data.get("core")
    if isinstance(core, dict) and core.get("output") == "text":
        core["output"] = "basic"
    config = Config(data, path=path)
    config.validate()
    return config


def load(
    config_path: Optional[Path] = None,
    *,
    env: Optional[Mapping[str, str]] = None,
    overrides: Optional[Mapping[str, Mapping[str, Any]]] = None,
) -> Config:
    file_data = read_yaml(config_path) if config_path else {}
    return resolve(file_data=file_data, env=env, overrides=overrides, path=config_path)
