---
apiVersion: v1
kind: Namespace
metadata:
  name: eda-playground
  labels:
    app.kubernetes.io/name: eda-playground
    app.kubernetes.io/managed-by: aap-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eda-playground-sa
  namespace: eda-playground
  labels:
    app.kubernetes.io/name: eda-playground
